In [87]:
import os
import numpy as np 
import pandas as pd

In [88]:
X_train = pd.read_csv("data/ancestry_train.data", sep = " ", header=None).values
y_train = pd.read_csv("data/ancestry_train.solution", sep = " ", header=None).values

X_test = pd.read_csv("data/ancestry_test.data", sep = " ", header=None).values

In [89]:
X_train

array([[0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [90]:
np.round(y_train, 3)

array([[0.198, 0.75 , 0.052],
       [0.858, 0.142, 0.   ],
       [0.761, 0.237, 0.001],
       ...,
       [0.001, 0.183, 0.817],
       [0.016, 0.591, 0.393],
       [0.   , 0.007, 0.993]])

In [91]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 2, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 1, 1],
       [0, 0, 2, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

# cost function

In [92]:
def cost(y_true, y_hat):
    mse = -np.log10(np.mean((y_true-y_hat)**2)+1e-5)
    return(mse)

# baseline

In [93]:
from sklearn.linear_model import Ridge

X_train_clean = []

for row in X_train:
    zero, one, two = 0, 0, 0
    for snp in row:
        if snp == 0:
            zero += 1
        elif snp == 1:
            one += 1
        elif snp == 2:
            two += 1
    X_train_clean.append([zero, one, two])

X_test_clean = []

for row in X_test:
    zero, one, two = 0, 0, 0
    for snp in row:
        if snp == 0:
            zero += 1
        elif snp == 1:
            one += 1
        elif snp == 2:
            two += 1
    X_test_clean.append([zero, one, two])

In [94]:
# y_test = np.ones((X_test.shape[0], y_train.shape[1])) * (1/3)

# from sklearn.neighbors import KNeighborsRegressor

# # clf = Ridge(alpha=1000)
# clf = KNeighborsRegressor(1500)

# clf.fit(X_train, y_train)
# y_test = clf.predict(X_test)

# base = np.ones((y_train.shape[0], y_train.shape[1])) * (1/3)
# cost(y_train, base)

In [141]:
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.InputLayer(input_shape=(500, )))
# model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dense(128, activation='relu'))
# model.add(tf.keras.layers.Dense(100, activation='relu'))
# model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(loss='mse', optimizer='adam', metrics=['mae'])
model.fit(X_train, y_train, epochs=10)

y_test = model.predict(X_test)

Epoch 1/10
1250/1250 [==============================] - 5s 3ms/step - loss: 0.0037 - mae: 0.0372
Epoch 2/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0024 - mae: 0.0306
Epoch 3/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0022 - mae: 0.0293
Epoch 4/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0021 - mae: 0.0284
Epoch 5/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0019 - mae: 0.0275
Epoch 6/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0018 - mae: 0.0268
Epoch 7/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0017 - mae: 0.0258
Epoch 8/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0015 - mae: 0.0243
Epoch 9/10
1250/1250 [==============================] - 4s 3ms/step - loss: 0.0014 - mae: 0.0231
Epoch 10/10
313/313 [==============================] - 1s 2ms/step


# save and zip the file

In [142]:
pd.DataFrame(y_test).to_csv(f"predictions.csv", sep = " ", header = None, index = None)
os.system("zip -r predictions.zip predictions.csv")

updating: predictions.csv (deflated 56%)


0